version: '3.8'

services:
  hangfire-postgres:
    image: postgres:15
    container_name: hangfire-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  hangfireapp:
    container_name: hangfireapp
    build:
      context: .
      network: host
    env_file:
      - .env
    depends_on:
      hangfire-postgres:
        condition: service_healthy
    ports:
      - "5000:8080"

volumes:
  pgdata:
